[project]
name = "pyls-smarter"
version = "0.1"
dependencies = ["PyQt5==5.15.10"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.scripts]
pyls = "pyls:main"